### ISSUE TITLE
third

### ISSUE THREAD

**Issue by azaroche** [Bitp-Spbsu/openstack-packstack#7]
Command line:
{
]# packstack --answer-file=/root/packstack-answers.3.ceph.V 
}
Finish:
{
 ***\* Installation completed successfully ******

Additional information:
- Deprecated parameter has been used in answer file. Please use parameter CONFIG_MARIADB_INSTALL next time. This parameter deprecates following parameters: ['CONFIG_MYSQL_INSTALL'].
- Deprecated parameter has been used in answer file. Please use parameter CONFIG_MARIADB_HOST next time. This parameter deprecates following parameters: ['CONFIG_MYSQL_HOST'].
- Deprecated parameter has been used in answer file. Please use parameter CONFIG_MARIADB_USER next time. This parameter deprecates following parameters: ['CONFIG_MYSQL_USER'].
- Deprecated parameter has been used in answer file. Please use parameter CONFIG_MARIADB_PW next time. This parameter deprecates following parameters: ['CONFIG_MYSQL_PW'].
- File /root/keystonerc_admin has been created on OpenStack client host 192.168.200.11. To use the command line tools you need to source the file.
- NOTE : A certificate was generated to be used for ssl, You should change the ssl certificate configured in /etc/httpd/conf.d/ssl.conf on 192.168.200.11 to use a CA signed cert.
- To access the OpenStack Dashboard browse to https://192.168.200.11/dashboard .
  Please, find your login credentials stored in the keystonerc_admin in your home directory.
  }

Check answer file:
{
]# grep CONFIG_STORAGE_HOST /root/packstack-answers.3.ceph.V
CONFIG_STORAGE_HOST=192.168.200.15,192.168.200.18,192.168.200.23
}

check ceph:
{
[root@alice15 openstack-packstack]# ssh 192.168.200.15 "ceph status"
bash: ceph: command not found
[root@alice15 openstack-packstack]# ssh 192.168.200.11 "ceph status"
    cluster 67c99046-4479-407a-83bc-94d82c421333
     health HEALTH_WARN 704 pgs stale; 704 pgs stuck stale; mds alice01.cloud.spbu.ru is laggy; 1/1 in osds are down
     monmap e1: 1 mons at {alice01=192.168.200.11:6789/0}, election epoch 1, quorum 0 alice01
     mdsmap e5: 1/1/1 up {0=alice01.cloud.spbu.ru=up:active(laggy or crashed)}
     osdmap e11: 1 osds: 0 up, 1 in
      pgmap v76: 704 pgs, 7 pools, 1884 bytes data, 20 objects
            5441 MB used, 3998 MB / 9951 MB avail
                 704 stale+active+clean
[root@alice15 openstack-packstack]#  
}

Ceph only on the one the one node, controller node:
{
[root@alice15 openstack-packstack]# grep 192.168.200.11 /root/packstack-answers.3.ceph.V
CONFIG_CONTROLLER_HOST=192.168.200.11
CONFIG_AMQP_HOST=192.168.200.11
CONFIG_MYSQL_HOST=192.168.200.11
[root@alice15 openstack-packstack]# 
}

**Comment by yuw726** [comment]
Fixed.
